# Generated by Django 3.2.6 on 2021-08-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.commoninfo')),
                ('content', models.TextField()),
                ('up_votes', models.PositiveBigIntegerField(default=0)),
                ('comment_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.commoninfo')),
            ],
            bases=('posts.commoninfo', models.Model),
        ),
    ]
