# Generated by Django 3.2.6 on 2021-08-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.comment'),
        ),
    ]
